### ISSUE TITLE
ImportError: /data/bbbbb/LearnableTreeFilterV2v/cvpods/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z39tree_filter_refine_backward_edge_weightRKN2at6TensorES2_S2_S2_S2_S2_S2_S2_S2_

### ISSUE THREAD

**Issue by fengenxiang1123** [StevenGrove/LearnableTreeFilterV2#7]
When I execute "from cvpods.layers import TreeFilterV2", there is a problem. The detailed error is as follows: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/__init__.py", line 3, in <module>
    from .utils import setup_environment
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/utils/__init__.py", line 27, in <module>
    from .visualizer import ColorMode, VideoVisualizer, VisImage, Visualizer, colormap, random_color
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/utils/visualizer/__init__.py", line 5, in <module>
    from .video_visualizer import *
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/utils/visualizer/video_visualizer.py", line 6, in <module>
    from .visualizer import ColorMode, Visualizer, _create_text_labels, _PanopticPrediction
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/utils/visualizer/visualizer.py", line 17, in <module>
    from cvpods.structures import BitMasks, Boxes, BoxMode, Keypoints, PolygonMasks, RotatedBoxes
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_ioa, pairwise_iou
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/structures/boxes.py", line 11, in <module>
    from cvpods.layers import cat
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/layers/__init__.py", line 4, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/data/bbbbb/LearnableTreeFilterV2v/cvpods/layers/deform_conv.py", line 11, in <module>
    from cvpods import _C
ImportError: /data/bbbbb/LearnableTreeFilterV2v/cvpods/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z39tree_filter_refine_backward_edge_weightRKN2at6TensorES2_S2_S2_S2_S2_S2_S2_S2_

**Comment by StevenGrove** [comment]
It seems the cuda codes of tree filter has not been compiled successfully. It could be using different cuda version for pytorch and nvcc. You can recompile the code by runing "python3 setup.py build develop --user" and check if it has similar issues.
